// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1, arg2) {
  return window['go']['main']['App']['AddRecentFile'](arg1, arg2);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CreateWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspaceFile'](arg1, arg2, arg3);
}

export function CreateWorkspaceFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspaceFolder'](arg1, arg2, arg3);
}

export function DeleteWorkspaceEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspaceEntry'](arg1, arg2);
}

export function ExportMarkdownAsPDF(arg1) {
  return window['go']['main']['App']['ExportMarkdownAsPDF'](arg1);
}

export function ListRecentFiles(arg1) {
  return window['go']['main']['App']['ListRecentFiles'](arg1);
}

export function LoadImageDataURL(arg1) {
  return window['go']['main']['App']['LoadImageDataURL'](arg1);
}

export function OpenMarkdownFile() {
  return window['go']['main']['App']['OpenMarkdownFile']();
}

export function OpenMarkdownFileAtPath(arg1) {
  return window['go']['main']['App']['OpenMarkdownFileAtPath'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function MoveWorkspaceEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveWorkspaceEntry'](arg1, arg2, arg3);
}

export function SearchWorkspaceContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchWorkspaceContent'](arg1, arg2, arg3);
}

export function ReplaceWorkspaceContent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReplaceWorkspaceContent'](arg1, arg2, arg3, arg4, arg5);
}

export function PreviewWorkspaceReplace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewWorkspaceReplace'](arg1, arg2, arg3, arg4);
}

export function ReplaceWorkspaceContentByPaths(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ReplaceWorkspaceContentByPaths'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RenameWorkspaceEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameWorkspaceEntry'](arg1, arg2, arg3);
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function ResolveImageDataURL(arg1, arg2) {
  return window['go']['main']['App']['ResolveImageDataURL'](arg1, arg2);
}

export function ListWorkspaceEntries(arg1, arg2) {
  return window['go']['main']['App']['ListWorkspaceEntries'](arg1, arg2);
}

export function SaveImageAsset(arg1) {
  return window['go']['main']['App']['SaveImageAsset'](arg1);
}

export function SaveMarkdownFile(arg1) {
  return window['go']['main']['App']['SaveMarkdownFile'](arg1);
}

export function SetDirtyState(arg1) {
  return window['go']['main']['App']['SetDirtyState'](arg1);
}
