// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1, arg2) {
  return window['go']['main']['App']['AddRecentFile'](arg1, arg2);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ExportMarkdownAsPDF(arg1) {
  return window['go']['main']['App']['ExportMarkdownAsPDF'](arg1);
}

export function ListRecentFiles(arg1) {
  return window['go']['main']['App']['ListRecentFiles'](arg1);
}

export function LoadImageDataURL(arg1) {
  return window['go']['main']['App']['LoadImageDataURL'](arg1);
}

export function OpenMarkdownFile() {
  return window['go']['main']['App']['OpenMarkdownFile']();
}

export function OpenMarkdownFileAtPath(arg1) {
  return window['go']['main']['App']['OpenMarkdownFileAtPath'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function ResolveImageDataURL(arg1, arg2) {
  return window['go']['main']['App']['ResolveImageDataURL'](arg1, arg2);
}

export function SaveImageAsset(arg1) {
  return window['go']['main']['App']['SaveImageAsset'](arg1);
}

export function SaveMarkdownFile(arg1) {
  return window['go']['main']['App']['SaveMarkdownFile'](arg1);
}

export function SetDirtyState(arg1) {
  return window['go']['main']['App']['SetDirtyState'](arg1);
}
